version: 2
updates:
  - package-ecosystem: npm
    directory: /football-cards-ui
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
