version: 2
updates:
  - package-ecosystem: npm
    directory: /football-cards-ui
    schedule:
      interval: weekly
    groups:
      mui:
        patterns:
          - "@mui/*"
          - "@emotion/*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
